### ISSUE TITLE
Tests stopped running long ago (but were failing then)

### ISSUE THREAD

**Issue by rfay** [hanoii/ddev-z#1]
Due to Github's timeout with no commits, the tests here haven't run ages and may not be compatible with current DDEV.

Please consider
* Updating the tests.yml file to https://github.com/ddev/ddev-addon-template/blob/main/.github/workflows/tests.yml so that it doesn't time out any more.
* Getting the tests (or the add-on) working again.

If not, please consider removing the `ddev-get` label and probably update the README to say that it's no longer maintained. 

Thanks!
-Randy

**Comment by hanoii** [comment]
Updated and archived.
